### ISSUE TITLE
Error in package repository: schema version is not a valid number

### ISSUE THREAD

**Issue by natefinch** [golang/sublime-build#1]
I tried to add https://packagecontrol.io/testing/go_packages.json as a package repository, but I get this error:

> Package Control: Repository https://packagecontrol.io/testing/go_packages.json does not appear to be a valid repository file because  the "schema_version" is not a valid number.

I'm on Sublime Text 3 version: 3083 linux x64 channel: stable

**Comment by wbond** [comment]
This almost certainly means you are using an old version of Package Control. If you run the "List Packages" command, what version is listed for Package Control?

**Comment by natefinch** [comment]
v2.0.0 alpha12 .. evidently an old version (though I don't actually see what the current version is on packagecontrol.io)

**Comment by wbond** [comment]
Yeah, you are mostly likely stuck on the alpha due to a self-updating bug. The instructions at https://packagecontrol.io/docs/troubleshooting#Purging_and_Reinstalling should help.

**Comment by natefinch** [comment]
Purge and reinstall worked perfectly, thanks!

**Comment by natefinch** [comment]
Might be worth a comment in the readme that this requires package control 3.x ... though maybe I'm the only one still stuck on 2.x

**Comment by wbond** [comment]
Only old alpha users with broken installs are on 2.x. No packages other than Package Control itself are available to users running Package Control older than 3.0. Also, this issue will not be present once the package is added to the default channel.

**Comment by lostingz** [comment]
reinstall worked successfully
