### ISSUE TITLE
Documentation Title Links Don't Work on go.googlesource.com

### ISSUE THREAD

**Issue by wbond** [golang/sublime-build#10]
The package currently directs users to https://go.googlesource.com/sublime-build/+/master/docs/configuration.md to help with configuration issues.

Unfortunately GitHub and go.googlesource.com use different patterns for generating the ids used for title links. On GitHub they are all lower case and on go.googlesource.com they are capitalized.

Two options:
1. Rewrite links to work with go.googlesource.com, breaking GitHub
2. Change plugin to direct users to GitHub version of docs, keeping links on go.googlesource.com broken

I'm inclined towards option 2 since I believe more people are likely to find the package on GitHub, since that is there Package Control will link to.

**Comment by wbond** [comment]
Thoughts @jbuberel?

**Comment by jbuberel** [comment]
We definitely do want all links to point to the github.com version. We should not have any end-user links referring to go.googlesource.com.

**Comment by wbond** [comment]
https://go-review.googlesource.com/#/c/16449/
