### ISSUE TITLE
Unable to cancel build with `go run`

### ISSUE THREAD

**Issue by jbuberel** [golang/sublime-build#12]
1. I opened my Project, which is rooted in my `$GOPATH/src` directory.
2. I navigated to the `gometrics.go` command from my https://github.com/jbuberel/gometrics/ project.
3. I execute 'Tools -> Build with...' and select `Go: Run`
4. The command begins to execute, with output visible in the console.
5. The 'Tools -> Cancel Build' menu item is disabled.
6. Pressing Ctrl-C does not terminate the running process.

Screenshot here:
![screen shot 2015-10-29 at 3 48 51 pm](https://cloud.githubusercontent.com/assets/1711364/10834289/6426778e-7e55-11e5-8d97-671d72c443c7.png)

**Comment by wbond** [comment]
Unfortunately the ST API doesn't allow hooking into the Cancel menu item with a custom build command. Instead you have to use the Go: Cancel Build command palette entry. Ctrl-c is bound in ST to show the current scope.

The only way to Improve this would be to possibly add our own menu item for cancelling a Go build. However it would show all the time - just disabled when no go build was running.

**Comment by jbuberel** [comment]
Is it possible to change the binding for Ctrl-C to invoke 'Go: Cancel Build' in the user's global/project settings?

Perhaps we could include that in the installation guide as a 'Suggested customization to make killing programs easier'?

In either case, we should definitely address that in the documentation. If you like, I can take a swing at writing it up.

**Comment by wbond** [comment]
Canceling a build is covered in the usage docs, but perhaps we should make an extra mention when discussing Run. I guess this is one of the usability downsides to adding Run support.

Personally I'm not a fan of recommending ctrl-c. That is copy on two of the three supported platforms.

**Comment by jbuberel** [comment]
That makes sense to me. Let me take a look through the docs, and see if
there's a place where calling this out should be more visible.

Now that I know, it's definitely not a big deal. But I (like many end
users) did not read the docs carefully enough to have noted this.

**Comment by wbond** [comment]
Yeah, I think that is understandable. Noticing the docs on canceling isn't something I would expect. I just know since I built it. :-)

**Comment by jbuberel** [comment]
New documentation added to help explain this behavior in v0.8.7
