### ISSUE TITLE
Cannot navigate from build errors to source code location if you have add -cover flag

### ISSUE THREAD

**Issue by grange74** [golang/sublime-build#15]
Normally clicking on a build error takes me to the source code location but after i added the -cover to my `test:flags` settings it just opens an empty file. Strangely it works if my error is in a test file but not if in a source file. 

Normally when it works i get an output similar to this:

```
> Environment:
>   GOPATH=/Users/me/go
> Directory: /Users/me/go/src/github.com/me/sample-project
> Command: /usr/local/go/bin/go test -v
> Output:
# github.com/me/sample-project
./somecode.go:33: undefined: fda
FAIL    github.com/me/sample-project [build failed]
> Elapsed: 0.090s
> Result: Error
```

After adding the -cover flag i get and clicking on the build error opens an empty file.

```
> Environment:
>   GOPATH=/Users/me/go
> Directory: /Users/me/go/src/github.com/me/sample-project
> Command: /usr/local/go/bin/go test -v -cover
> Output:
# github.com/me/sample-project
/var/folders/yk/vz2vyqg51g38dbb20l9jjqpc0000gn/T/go-build616091459/github.com/me/sample-project/_test/_obj_test/somecode.go:41: undefined: fda
FAIL    github.com/me/sample-project [build failed]
> Elapsed: 0.151s
> Result: Error
```

If i remove the -cover flag, it works again.

Btw i'm running this is on OSX.

My golang.sublime-settings contains:

```
{
    "test:flags": ["-v", "-cover"]
}
```

**Comment by wbond** [comment]
If an empty file is opened, that makes me think that `go` is generating a temporary file, then cleaning it up, but reporting that temporary file path. It would seem to me that instead of that large temporary path, it should print the relative file path like the command not including `-cover`.

I'm inclined to think this is something that should be fixed in the `go` tool, but that is just based on a cursory glance.

**Comment by jbuberel** [comment]
@wbond Indeed, this is a temporary file that is removed by the Go tool when execution completes. There is no way I know of to disable this behavior. So there is no way to fix this in the Golang Build package.
