### ISSUE TITLE
Jump to error line 

### ISSUE THREAD

**Issue by pobearm** [golang/sublime-build#16]
I think,  jump to error line on mouse click from build message panel, is a good idea.
we can use this regex to  match the file and line from build error message:
(?<file>[\/0-9a-zA-Z\._]+):(?<line>\d+) 

example:
./demo.go:20: syntax error: unexpected literal 2, expecting semicolon or newline or

**Comment by wbond** [comment]
This was taken care of in #3

**Comment by pobearm** [comment]
ok, double click , thanks
