### ISSUE TITLE
sublime process freezing

### ISSUE THREAD

**Issue by pobearm** [golang/sublime-build#18]
On mac os x 11 , sublime 3(build 3083 newest version),   installed this plugin with package control,
When i open an empty sublime text,  then got 2 system process ,  one of them is freezing.

**Comment by wbond** [comment]
When you say you have two system processes, what do you mean? Are you referring to Sublime Text icons in the dock?

Does the non-frozen icon function properly?

**Comment by pobearm** [comment]
In Activity Monitor of mac os x, search "sublime", there are two processes, one of them is red(freezing).

**Comment by wbond** [comment]
Is there excessive memory usage or CPU usage?

Sublime Text does in fact use two processes, the GUI and a background process for the plugins to run in. The plugin process seems to expose itself to OS X when the newterm package uses AppleScript via AppKit to launch terminal windows.

Currently https://github.com/codexns/newterm/blob/master/all/newterm/_osx.py#L401-L406 exists to prevent a second dock icon from appearing.

Mostly what I am trying to figure out is if there is any actual negative side effect, or if OS X is just confused by the plugin process not being a full desktop app, but still interacting with AppKit. From my testing, I don't think there is. But I'd be very appreciative to hear if anyone else is having any issues.

**Comment by wbond** [comment]
@pobearm Did you ever get a chance to see if there was any excessive CPU usage from the second process? If there isn't, I am going to assume this is a side effect of newterm.

**Comment by wbond** [comment]
@jbuberel From my testing I don't believe it is an issue, and @pobearm seems to no longer be responding. You should be able to close this issue.

**Comment by pobearm** [comment]
sorry for delay!  
![qq20160111-0](https://cloud.githubusercontent.com/assets/13976397/12225321/604d9ebc-b843-11e5-8b27-cd150a323cf9.png)

**Comment by wbond** [comment]
You can confirm my analysis by comparing the PID in the activity monitor with the output from `ps awx | grep plugin_host`.

If Sublime Text and all of your plugins are running, and the PIDs are the same, this is a "bug" with OS X.

**Comment by jaggerwang** [comment]
![image](https://cloud.githubusercontent.com/assets/1255011/15651551/f3b8854e-26b2-11e6-90cd-7754eab06b8d.png)
I've the same problem for a long time. I'm using sublime text 3.
