### ISSUE TITLE
Cannot run build commands without the -v flag.

### ISSUE THREAD

**Issue by ChrisHines** [golang/sublime-build#2]
The build commands always append the `-v` flag. That is undoubtedly useful for `go install` but not always wanted for `go test`. The build system seems to append the `-v` flag independently of flags set in the Sublime configuration.

Can we have a way to run the build commands without `-v`?

**Comment by wbond** [comment]
How about if the flags are set via configuration they replace `-v` instead of appending after it?

**Comment by ChrisHines** [comment]
That sounds good. That's what I was expecting, actually.

**Comment by jbuberel** [comment]
https://go-review.googlesource.com/#/c/16252/

**Comment by jbuberel** [comment]
Confirmed with the 0.8.1 build, using the following project configuration:

```
     "settings": {
        "golang": {
            "install:flags": ["-x", "github.com/jbuberel/wikilinktester"],
        }
    }
```

The console output of running the 'install' command with this configuration confirmed that the -v flag was not used:

```
> Environment:
>   GOPATH=/Users/jbuberel/workspace-shared:/Users/jbuberel/workspace
> Directory: /Users/jbuberel/workspace/src/github.com/jbuberel/gometrics
> Command: /Users/jbuberel/go15/bin/go install -x github.com/jbuberel/wikilinktester
> Output:
WORK=/var/folders/t5/yk4tfq9166jcjr4pqt7qypfh004wn2/T/go-build934937765
> Elapsed: 3.926s
> Result: Success
```
