### ISSUE TITLE
Cycle through errors with F4

### ISSUE THREAD

**Issue by ghost** [golang/sublime-build#20]
Cycle through errors with F4

**Comment by wbond** [comment]
This should be available since it was added in 83e26fe4ce06343887df80c4b46a313d6c75fc4a

**Comment by wbond** [comment]
Can you see if shift+f4 works for you? I noticed looking at the results that f4 (forward) seems disabled by default, but shift+f4 (backwards) is enabled.

I am wondering if this is due to the cursor position in the output panel when the build process finishes. I'll look into it some more.

**Comment by ghost** [comment]
shift+f4 works fine. It puts the cursor on the line number and not the build window (yay!).

**Comment by ghost** [comment]
F4 works fine too actually. I had F4 overriden in my settings.
