### ISSUE TITLE
building always lands on the last error

### ISSUE THREAD

**Issue by ghost** [golang/sublime-build#21]
any build action always rests on the last error. Is that the desired build behavior? 
For example, if I use F4 to cycle to next error, I am greeted with the rebuke "no more results", this is b/c the build process always lands on the last result, and does not cycle to the first but ends on the last error.
 In my limited go experience I find sometimes a later error is caused by an earlier error, but I'd like to know if that's even relevant (as this only related to which error is first accessible using sublime-build, which as it is for me is always the last error). Would be curious to know what the preferred error to land on  should be, the first or last error received?

**Comment by dmitshur** [comment]
I'm not familiar with the context, but displaying the first (earliest) error, not last, seems like preferable behavior.
