### ISSUE TITLE
GOPATH not set with multi-entry GOPATH on Windows

### ISSUE THREAD

**Issue by jbuberel** [golang/sublime-build#4]
Executing build on `command.go` works correctly with this project config:

``` json
{
    "folders":
    [
        {
            "path": "C:\\Users\\jason\\workspace1"
        },
        {
            "path": "C:\\Users\\jason\\workspace2"
        }
    ],
    "settings": {
        "golang": {
            "windows": {
                "GOPATH": "C:\\Users\\jason\\workspace1"
            },
            "osx": {
                "GOPATH": "C:\\Users\\jason\\workspace2"
            }

        }
    }
}
```

But when I add a second entry to the `GOPATH` for windows as below...

``` json
{
    "folders":
    [
        {
            "path": "C:\\Users\\jason\\workspace1"
        },
        {
            "path": "C:\\Users\\jason\\workspace2"
        }
    ],
    "settings": {
        "golang": {
            "windows": {
                "GOPATH": "C:\\Users\\jason\\workspace1;C:\\Users\\jason\\workspace2"
            },
            "osx": {
                "GOPATH": "C:\\Users\\jason\\workspace2"
            }

        }
    }
}
```

I get the following error dialog:
![image](https://cloud.githubusercontent.com/assets/1711364/10623137/1f61db7c-7741-11e5-88c9-bdfc5854c222.png)

**Comment by wbond** [comment]
Are there any entries printed in the Sublime Text console?

**Comment by jbuberel** [comment]
No, nothing :-(

I also tried treating the `"GOPATH":` entry like a JSON array, but that didn't work either. Is there some other standard way of representing multi-part path entries on Sublime/Windows?

**Comment by wbond** [comment]
I was not aware that `GOPATH` could have multiple entries. At https://github.com/golang/sublime-config/blob/master/all/golangconfig.py#L288-L303, you'll see that we are testing to see if the value for `GOPATH` exists on the filesystem.

It appears to get the console output in this situation, the `debug` setting under `golang` needs to be set to `true.

Either way, I've opened golang/sublime-config#1 to track this issue.

**Comment by jbuberel** [comment]
https://go-review.googlesource.com/#/c/16251/1

**Comment by jbuberel** [comment]
I've confirmed this is now working correctly in the v0.8.1 release.
