### ISSUE TITLE
can't search build output

### ISSUE THREAD

**Issue by natefinch** [golang/sublime-build#5]
Whatever type of panel the build output is in evidently can't coexist with the search panel... which means I can't search the build output, which is kind of a deal breaker when I get huge quantities of text dumped during a test failure.

**Comment by wbond** [comment]
This is unfortunately the way that the Sublime Text UI works.

The only way I could imagine getting around this would be to add a command to open the build results in a normal editor view. This would require a new command that would need to be invoked by the user after a build completes.

**Comment by natefinch** [comment]
Wow, that's horrible.  I guess I can manually copy and paste, but man, that seems like a big drawback.  Ahh well, guess it can't all be perfect.  I don't know that it really needs a new command, ctrl-A ctrl-c will copy the whole contents of the pane anyway.

**Comment by jbuberel** [comment]
I agree that this is a regrettable limitation with ST3, but the opening build output  in a new editor window would be jarring and cause the current code editor to lose focus. 

As such, closing out this issue for now.
