### ISSUE TITLE
"Package Golang Build is not available" during installation

### ISSUE THREAD

**Issue by vladimirvivien** [golang/sublime-build#7]
Hello, great to see official support for sublime from the golang project.
However, I was not able to complete the installation, the package is not found.

1) What version of Go are you using (go version)?
go version go1.5.1 darwin/amd64
Sublime Text Stable Channel Build 3083

2) What operating system and processor architecture are you using?
OSX 10.10.5

3) What did you do?
- I installed the package manager
- I typed "Package Control: Install Package"
- I was presented with a list of available packages
- Type "Golang Build"

4) What did you expect to see?
The Golang Build sublime package to available.

5) What did you see instead?
No package with that name was available

6) I tried the advanced installation option, same result.

**Comment by vladimirvivien** [comment]
The package is not listed on the Package Control web site either 

https://packagecontrol.io/search/golang

**Comment by wbond** [comment]
This package is currently undergoing beta testing, so it has not been added to the default channel yet. https://forum.golangbridge.org/t/beta-testers-wanted-sublimetext-go/1282/15 has more details.

Sorry for the readme being confusing right now!

**Comment by webRat** [comment]
I would remove the section from the readme until it's available on https://packagecontrol.io/

**Comment by wbond** [comment]
@webRat Unfortunately I don't have the ability to do that right now. It seems the auto sync from https://go.googlesource.com/sublime-build/ is broken. For now this issue will have to do.

**Comment by jbuberel** [comment]
@vladimirvivien @webRat - We're getting very close (a few days) to having a build that we think is good enough to make available via the standard package control mechanisms. Once that happens, this should no longer be an issue (and the documentation on the Git repo will work correctly).

I'm going to close this issue for now, as it will be resolved in the next few days.
