### ISSUE TITLE
Support for "go run"

### ISSUE THREAD

**Issue by vladimirvivien** [golang/sublime-build#8]
I don't see support for `go run` of the box.
Looking at the code and test it looks it is a matter of specifying `task:run`.
If that is the case where do I specify that task so it will be available in sublime?
If it's a code change, where would that go ?

**Comment by jbuberel** [comment]
@vladimirvivien Good suggestion. Let me discuss this with @wbond to better understand the work involved to support `go run` as a build variant.

My concern is that the console where output is captured could get very large if your program was long running and produced verbose output.

**Comment by vladimirvivien** [comment]
@jbuberel valid concern.  However, one does hope that the programmer would be sensitive to the limitation of sublime as a terminal.  Having the ability to do quick tests with `go run` would greatly increase the usefulness of the project.  Thanks.

**Comment by jbuberel** [comment]
First CL to add this now in code review:
https://go-review.googlesource.com/#/c/16441

**Comment by vladimirvivien** [comment]
@jbuberel thanks for the quick response!

**Comment by wbond** [comment]
This is available as of version 0.8.5. You can use `Upgrade Package` from the command palette if `List Packages` shows that you do not have that version yet.

**Comment by jbuberel** [comment]
Verified the command is now available with 0.8.5.
